force-app/main/default/objects/Navigation_Carousel__c/Navigation_Carousel__c.object-meta.xml
<CustomObject>
    <label>Navigation Carousel</label>
    <nameField>
        <label>Navigation Carousel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Carousels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Navigation_Carousel__c/fields/IconSize__c.field-meta.xml
<CustomField>
    <fullName>IconSize__c</fullName>
    <description>The size of the icon. Options include xx-small, x-small, small, medium, or large. This value defaults to medium.</description>
    <inlineHelpText>The size of the icon. Options include xx-small, x-small, small, medium, or large. This value defaults to medium.</inlineHelpText>
    <label>IconSize</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel__c/fields/Page_Size_Large__c.field-meta.xml
<CustomField>
    <fullName>Page_Size_Large__c</fullName>
    <description>Number of navigation items visible at a time when displayed in a large viewport like a desktop monitor</description>
    <inlineHelpText>Number of navigation items visible at a time when displayed in a large viewport like a desktop monitor</inlineHelpText>
    <label>Page Size Large</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel__c/fields/Page_Size_Medium__c.field-meta.xml
<CustomField>
    <fullName>Page_Size_Medium__c</fullName>
    <description>Number of items per page when displayed in a medium size viewport such as a tablet</description>
    <inlineHelpText>Number of items per page when displayed in a medium size viewport such as a tablet</inlineHelpText>
    <label>Page Size Medium</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel__c/fields/Page_Size_Small__c.field-meta.xml
<CustomField>
    <fullName>Page_Size_Small__c</fullName>
    <description>Number of items per page when displayed in a small viewport such as a phone</description>
    <inlineHelpText>Number of items per page when displayed in a small viewport such as a phone</inlineHelpText>
    <label>Page Size Small</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/Navigation_Carousel_Item__c.object-meta.xml
<CustomObject>
    <label>Navigation Carousel Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Carousel Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Id_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Id_Parameter__c</fullName>
    <label>Id Parameter</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Image_Path__c.field-meta.xml
<CustomField>
    <fullName>Image_Path__c</fullName>
    <label>Image Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label that will appear in the navigation carousel for this item</description>
    <inlineHelpText>Label that will appear in the navigation carousel for this item</inlineHelpText>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Navigation_Carousel__c.field-meta.xml
<CustomField>
    <fullName>Navigation_Carousel__c</fullName>
    <label>Navigation Carousel</label>
    <referenceTo>Navigation_Carousel__c</referenceTo>
    <relationshipLabel>Navigation Carousel Items</relationshipLabel>
    <relationshipName>Navigation_Carousel_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Parameter__c.field-meta.xml
<CustomField>
    <fullName>Parameter__c</fullName>
    <description>Type: Value
Home: (Leave blank)
Object: API name of the object
Page: name of the page
Topic: Topic Nam</description>
    <inlineHelpText>Type: Value
Home: (Leave blank)
Object: API name of the object
Page: name of the page
Topic: Topic Nam</inlineHelpText>
    <label>Name Parameter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/recordTypes/Topic.recordType-meta.xml
<RecordType>
    <fullName>Topic</fullName>
    <active>true</active>
    <description>indicates a link to a Topic</description>
    <label>Topic</label>
</RecordType>

force-app/main/default/classes/NavigationCarouselService.cls
public class NavigationCarouselService { 

	@AuraEnabled
	public static NavigationCarousel getNavigationItems(string carouselName) {
		NavigationCarousel result;

		System.debug(carouselName);
		List<Navigation_Carousel__c> items = [select IconSize__c, Page_Size_Large__c, Page_Size_Medium__c, Page_Size_Small__c, (select RecordType.Name, Id_Parameter__c, Image_Path__c, Label__c, Parameter__c from Navigation_Carousel_Items__r) from Navigation_Carousel__c where Name = :carouselName];
		System.debug(items);

		if (0 < items.size()) {
			result = new NavigationCarousel(items[0]);
		}

		Map<Id, ConnectApi.Topic> topics = GetTopicsMap();
        system.debug(topics);
		for (NavigationCarouselItem nci : result.NavigationCarouselItems) {
			if (nci.RecordType.Name.toLowerCase() == 'topic') {
				nci.Label = topics.get(nci.IdParameter).Name;
			}
		}
		return result;
	}
    
	public static Map<Id, ConnectApi.Topic> GetTopicsMap() {
		Map<Id, ConnectApi.Topic> topicMap = new Map<Id, ConnectApi.Topic>();
		List<ConnectApi.Topic> topics = GetTopics();
		for (ConnectApi.Topic t : topics) {
			topicMap.put(t.Id, t);
		}
		return topicMap;
	}

	@AuraEnabled
	public static List<ConnectApi.Topic> GetTopics() {
		ConnectApi.TopicPage topicList = ConnectApi.Topics.getTopics(Network.getNetworkId(), 0, 100, ConnectApi.TopicSort.alphaAsc);
		return topicList.topics;
	}
    
	public class NavigationCarouselItem {
		@AuraEnabled public Id Id {get;set;}
		@AuraEnabled public string IdParameter {get;set;}
		@AuraEnabled public string ImagePath {get;set;}
		@AuraEnabled public string Label {get;set;}
		@AuraEnabled public string Parameter {get;set;}
		@AuraEnabled public RecordType RecordType {get;set;}

		public NavigationCarouselItem(Navigation_Carousel_Item__c data) {
			Id = data.Id;
			IdParameter = data.Id_Parameter__c;
			ImagePath = data.Image_Path__c;
			Label = data.Label__c;
			Parameter = data.Parameter__c;
			RecordType = data.RecordType;
		}
	}

	public class NavigationCarousel {
		@AuraEnabled public Id Id {get;set;}
		@AuraEnabled public List<NavigationCarouselItem> NavigationCarouselItems {get; set;}
		@AuraEnabled public Integer PageSizeSmall {get;set;}
		@AuraEnabled public Integer PageSizeMedium {get;set;}
		@AuraEnabled public Integer PageSizeLarge {get;set;}
        @AuraEnabled public String IconSize {get;set;}

		public NavigationCarousel() {
			NavigationCarouselItems = new List<NavigationCarouselItem>();
		}

		public NavigationCarousel(Navigation_Carousel__c data) {
			Id = data.Id;
			PageSizeSmall = Integer.valueOf(data.Page_Size_Small__c);
			PageSizeMedium = Integer.valueOf(data.Page_Size_Medium__c);
			PageSizeLarge = Integer.valueOf(data.Page_Size_Large__c);
            IconSize = String.valueOf(data.IconSize__c);

			NavigationCarouselItems = new List<NavigationCarouselItem>();
			for(Navigation_Carousel_Item__c nci : data.Navigation_Carousel_Items__r) {
				NavigationCarouselItems.add(new NavigationCarouselItem(nci));
			}
		}
	}
}