force-app/main/default/objects/Navigation_Carousel__c/Navigation_Carousel__c.object-meta.xml
<CustomObject>
    <label>Navigation Carousel</label>
    <nameField>
        <label>Navigation Carousel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Carousels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Navigation_Carousel__c/fields/IconSize__c.field-meta.xml
<CustomField>
    <fullName>IconSize__c</fullName>
    <description>The size of the icon. Options include xx-small, x-small, small, medium, or large. This value defaults to medium.</description>
    <inlineHelpText>The size of the icon. Options include xx-small, x-small, small, medium, or large. This value defaults to medium.</inlineHelpText>
    <label>IconSize</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel__c/fields/Page_Size_Large__c.field-meta.xml
<CustomField>
    <fullName>Page_Size_Large__c</fullName>
    <description>Number of navigation items visible at a time when displayed in a large viewport like a desktop monitor</description>
    <inlineHelpText>Number of navigation items visible at a time when displayed in a large viewport like a desktop monitor</inlineHelpText>
    <label>Page Size Large</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel__c/fields/Page_Size_Medium__c.field-meta.xml
<CustomField>
    <fullName>Page_Size_Medium__c</fullName>
    <description>Number of items per page when displayed in a medium size viewport such as a tablet</description>
    <inlineHelpText>Number of items per page when displayed in a medium size viewport such as a tablet</inlineHelpText>
    <label>Page Size Medium</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel__c/fields/Page_Size_Small__c.field-meta.xml
<CustomField>
    <fullName>Page_Size_Small__c</fullName>
    <description>Number of items per page when displayed in a small viewport such as a phone</description>
    <inlineHelpText>Number of items per page when displayed in a small viewport such as a phone</inlineHelpText>
    <label>Page Size Small</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/Navigation_Carousel_Item__c.object-meta.xml
<CustomObject>
    <label>Navigation Carousel Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Carousel Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Id_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Id_Parameter__c</fullName>
    <label>Id Parameter</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Image_Path__c.field-meta.xml
<CustomField>
    <fullName>Image_Path__c</fullName>
    <label>Image Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label that will appear in the navigation carousel for this item</description>
    <inlineHelpText>Label that will appear in the navigation carousel for this item</inlineHelpText>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Navigation_Carousel__c.field-meta.xml
<CustomField>
    <fullName>Navigation_Carousel__c</fullName>
    <label>Navigation Carousel</label>
    <referenceTo>Navigation_Carousel__c</referenceTo>
    <relationshipLabel>Navigation Carousel Items</relationshipLabel>
    <relationshipName>Navigation_Carousel_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/fields/Parameter__c.field-meta.xml
<CustomField>
    <fullName>Parameter__c</fullName>
    <description>Type: Value
Home: (Leave blank)
Object: API name of the object
Page: name of the page
Topic: Topic Nam</description>
    <inlineHelpText>Type: Value
Home: (Leave blank)
Object: API name of the object
Page: name of the page
Topic: Topic Nam</inlineHelpText>
    <label>Name Parameter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Navigation_Carousel_Item__c/recordTypes/Object.recordType-meta.xml
<RecordType>
    <fullName>Object</fullName>
    <active>true</active>
    <description>indicates a link to an object page</description>
    <label>Object</label>
</RecordType>

force-app/main/default/classes/NavigationCarouselServiceTest.cls
@isTest 
private class NavigationCarouselServiceTest {

	@isTest(SeeAllData=true)
	private static void getNavigationItems() {
		Navigation_Carousel__c nc = new Navigation_Carousel__c();
		nc.IconSize__c = 'Small';
		nc.Name = 'TestCarousel';
		nc.Page_Size_Large__c = 8;
		nc.Page_Size_Medium__c = 4;
		nc.Page_Size_Small__c = 2;
		insert nc;

		List<Navigation_Carousel_Item__c> items = new List<Navigation_Carousel_Item__c>();
		for (Integer x = 0; x < 9; x++) {
			String xstr = String.valueOf(x);
			Navigation_Carousel_Item__c nci = new Navigation_Carousel_Item__c();
			nci.Id_Parameter__c = xstr;
			nci.Image_Path__c = '/path/' + xstr;
			nci.Label__c = 'Label ' + xstr;
			nci.Name = 'Name ' + xstr;
			nci.Navigation_Carousel__c = nc.Id;
			nci.Parameter__c = xstr;
			nci.RecordTypeId = Schema.SObjectType.Navigation_Carousel_Item__c.getRecordTypeInfosByName().get('Object').getRecordTypeId();
			items.add(nci);
		}
		insert items;

		Test.startTest();
		NavigationCarouselService.NavigationCarousel nctest = NavigationCarouselService.getNavigationItems(nc.Name);
		Test.stopTest();

		System.assertEquals(nc.IconSize__c, nctest.IconSize);
		System.assertEquals(Integer.valueOf(nc.Page_Size_Large__c), nctest.PageSizeLarge);
		System.assertEquals(Integer.valueOf(nc.Page_Size_Medium__c), nctest.PageSizeMedium);
		System.assertEquals(Integer.valueOf(nc.Page_Size_Small__c), nctest.PageSizeSmall);

		System.assertEquals(items.size(), nctest.NavigationCarouselItems.size());

	}
}